Bluetooth controls
DIT112-V19/group-11 pull request #29
Opened 2019-04-29 13:03 UTC by Wagajay

## Description
added Bluetooth controls 
## Related issue(s)

2019-04-29 13:04 UTC, JoakimDeak approved these changes
code works after trying with the car

2019-04-29 13:08 UTC, platisd requested changes

2019-04-29 13:08 UTC, platisd commented on SmartCar.ino
> +SoftwareSerial BTSerial(0, 1);
Why are you not just using the normal Serial?

2019-04-29 13:08 UTC, platisd commented on SmartCar.ino
> +      upSpeed(&speed);
No need to overcomplicate things with pointers and references, especially when they are not needed.
For example, if you really want to pass `speed` as an argument, despite it being a global variable and therefore accessible from everywhere, your method signatures should probably look something like this:
```
cpp
void upSpeed(int& speed2) {
 speed2 += 20;
}
```
And then used as `upSpeed(speed);`. But in any case, you should decide whether you need a global variable or not.

2019-05-01 10:49 UTC, TobiasBanck submitted a review, later dismissed

2019-05-03 10:41 UTC, closed without merging